// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    BlogHeader: typeof import("./src/components/BlogHeader.vue")["default"]
    BlogListItem: typeof import("./src/components/BlogListItem.vue")["default"]
    Loading: typeof import("./src/components/Loading.vue")["default"]
    ProjectGridItem: typeof import("./src/components/ProjectGridItem.vue")["default"]
  }
}

export {}
