// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    AAvatar: typeof import("ant-design-vue/es")["Avatar"]
    ACol: typeof import("ant-design-vue/es")["Col"]
    ACollapse: typeof import("ant-design-vue/es")["Collapse"]
    ACollapsePanel: typeof import("ant-design-vue/es")["CollapsePanel"]
    AList: typeof import("ant-design-vue/es")["List"]
    AListItem: typeof import("ant-design-vue/es")["ListItem"]
    ARow: typeof import("ant-design-vue/es")["Row"]
    BlogHeader: typeof import("./src/components/BlogHeader.vue")["default"]
  }
}

export {}
