// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BlogFrontMatter: typeof import('./../components/blog/front-matter.vue')['default']
    Loading: typeof import('./../components/loading.vue')['default']
    Markdown: typeof import('./../components/markdown/index.vue')['default']
    ResumeExpGallery: typeof import('./../components/resume/exp-gallery.vue')['default']
    ResumeProfile: typeof import('./../components/resume/profile.vue')['default']
    ResumeProjectGallery: typeof import('./../components/resume/project-gallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SymbolsGithub: typeof import('./../components/symbols/github.vue')['default']
    Tile: typeof import('./../components/tile.vue')['default']
    ToggleButton: typeof import('./../components/toggle-button.vue')['default']
  }
}
